WIP Upgrade pytorch to newer version
Currently, this fails `sbt test` due to (probably) some Cuda library
missing:

java.lang.RuntimeException: Could not run 'aten::empty_strided' with
arguments from the 'CUDA' backend.